Update frontend.jenkinsfile

diff --git a/frontend.jenkinsfile b/frontend.jenkinsfile
--- a/frontend.jenkinsfile
+++ b/frontend.jenkinsfile
@@ -30,12 +30,13 @@ pipeline {
                 sshagent (credentials: ['app-ec2-key']) {
                     withCredentials([usernamePassword(credentialsId: 'dockerhubCredentials', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                         sh '''
-                        ssh -o StrictHostKeyChecking=no ubuntu@$APP_EC2_IP << EOF
+                        ssh -o StrictHostKeyChecking=no ubuntu@$APP_EC2_IP << 'ENDSSH'
                           docker login -u $DOCKER_USER -p $DOCKER_PASS
-                          docker stop frontend || true && docker rm frontend || true
+                          docker stop frontend || true
+                          docker rm frontend || true
                           docker pull $DOCKER_USER/mern_app:frontend
                           docker run -d --name frontend -p 80:80 $DOCKER_USER/mern_app:frontend
-                        EOF
+                        ENDSSH
                         '''
                     }
                 }
@@ -45,10 +46,10 @@ pipeline {
 
     post {
         success {
-            echo 'Frontend Deployed Successfully!'
+            echo '✅ Frontend Deployed Successfully!'
         }
         failure {
-            echo 'Frontend Deployment Failed!'
+            echo '❌ Frontend Deployment Failed!'
         }
     }
 }
